name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.13.2'
          cache: 'yarn'

      - name: Install packages
        run: yarn install

      - name: Build + Deploy to Surge
        run: yarn deploy --token ${{secrets.SURGE_TOKEN}}
